version: 2.1
orbs:
  codecov: codecov/codecov@3.1.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvnw test
      - codecov/upload

workflows:
  sample:
    jobs:
      - build-and-test